---
# External DNS Ref: https://artifacthub.io/packages/helm/external-dns/external-dns
# yaml-language-server: $schema=https://github.com/kubernetes-sigs/external-dns/raw/refs/heads/master/charts/external-dns/values.schema.json

# Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?var-datasource=default&var-cluster=&var-namespace=external-dns&var-workload=external-dns&var-type=All&orgId=1&refresh=10s&from=now-30d&to=now
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 96Mi
    ephemeral-storage: 128Mi
