---
argument_specs:
  # roles/myapp/tasks/main.yml entry point
  main:
    options:
      whats_up_docker_apps_fast_data_dir:
        type: path
        required: true
      whats_up_docker_apps_safe_data_dir:
        type: path
        required: true
      whats_up_docker_apps_dockge_stacks_dir:
        type: path
        required: true
      whats_up_docker_data_dir:
        type: path
        required: true
