---
services:
  satisfactory-server:
    container_name: "satisfactory-server"
    hostname: "satisfactory-server"
    image: ghcr.io/wolveix/satisfactory-server:v1.9.7
    ports:
      - "7777:7777/tcp"
      - "7777:7777/udp"
      - "8888:8888/tcp"
    volumes:
      - "./satisfactory-server:/config"
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
