---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: "/tf-infra/digitalocean/sfo3"
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: "/tf-infra/digitalocean/sfo3/k8s"
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: "/tf-infra/vault"
    schedule:
      interval: daily
