---
# Dependabot Config: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: docker-compose
    directories:
      - ansible/docker/*
    schedule:
      interval: daily
    groups:
      docker-compose:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    groups:
      pip:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directories:
      - infra/digitalocean/**/terraform
      - infra/k8s/**/terraform
      - infra/k8s/**/modules/*
      - infra/proxmox/**/terraform
      - infra/proxmox/**/modules/*
      - infra/tailscale/terraform
      - infra/tfcloud/terraform
      - infra/unifi/terraform
    schedule:
      interval: daily
    groups:
      terraform-remote-exec:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directories:
      - infra/secrets/terraform
      - infra/secrets/terraform/modules/*
    schedule:
      interval: daily
    groups:
      terraform-local-exec:
        patterns:
          - "*"
    ignore:
      # Cloudflare provider version 5 doesn't have a clear upgrade path from version 4.
      - dependency-name: cloudflare/cloudflare
        update-types:
          - version-update:semver-major
