---
# Dependabot Config: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: docker
    directories:
      # TODO: replace this list with a wildcard expression
      - ansible/docker/homepage/compose.yaml
      - ansible/docker/satisfactory-server/compose.yaml
      - ansible/docker/tfc-agent/compose.yaml
      - ansible/docker/tsdproxy/compose.yaml
      - ansible/docker/uptime-kuma/compose.yaml
      - ansible/docker/whatsupdocker/compose.yaml
    schedule:
      interval: daily
    groups:
      pip:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    groups:
      pip:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directories:
      - digitalocean/**/terraform
      - homelab/**/terraform
      - homelab/**/terraform/modules/*
      - homelab/**/terraform/modules/**/modules/*
      - tailscale/terraform
      - tfcloud/terraform
      - unifi/terraform
    schedule:
      interval: daily
    groups:
      terraform-remote-exec:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directories:
      - secrets/terraform
      - secrets/terraform/modules/*
    schedule:
      interval: daily
    groups:
      terraform-local-exec:
        patterns:
          - "*"
