---
# Dependabot Config: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    groups:
      pip:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directories:
      - digitalocean/terraform
      - digitalocean/nyc3/terraform
    schedule:
      interval: daily
    groups:
      terraform-digitalocean:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directories:
      - digitalocean/nyc3/do-k8s/terraform
    schedule:
      interval: daily
    groups:
      terraform-k8s:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directories:
      - tfcloud/terraform
    schedule:
      interval: daily
    groups:
      terraform-tfcloud:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directories:
      - secrets/terraform
    schedule:
      interval: daily
    groups:
      terraform-secrets:
        patterns:
          - "*"
