---
# Dependabot Config: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: docker-compose
    directories:
      - ansible/docker/*
    schedule:
      interval: daily
    groups:
      pip:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    groups:
      pip:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directories:
      - digitalocean/**/terraform
      - homelab/**/terraform
      - homelab/**/terraform/modules/*
      - homelab/**/terraform/modules/**/modules/*
      - tailscale/terraform
      - tfcloud/terraform
      - unifi/terraform
    schedule:
      interval: daily
    groups:
      terraform-remote-exec:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directories:
      - secrets/terraform
      - secrets/terraform/modules/*
    schedule:
      interval: daily
    groups:
      terraform-local-exec:
        patterns:
          - "*"
