---
# Dependabot Config: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    groups:
      pip:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directories:
      - digitalocean/terraform
      - digitalocean/nyc3/terraform
      - digitalocean/nyc3/do-k8s/terraform
      - tailscale/terraform
      - tfcloud/terraform
    schedule:
      interval: daily
    groups:
      terraform-remote-exec:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directories:
      - homelab/terraform
      - homelab/terraform/modules/cilium
      - homelab/terraform/modules/cluster_operators
      - homelab/terraform/modules/cluster_services
      - homelab/terraform/modules/monitoring_stack
      - homelab/terraform/modules/rook_ceph
      - proxmox/terraform
      - proxmox/terraform/modules/proxmox_cloudinit_vm
      - proxmox/terraform/modules/proxmox_cloudinit_vm/modules/unifi_host_dns_records
      - secrets/terraform
      - secrets/terraform/modules/gh_secrets
      - secrets/terraform/modules/proxmox_secrets
      - secrets/terraform/modules/tfe_secrets
      - unifi/terraform
    schedule:
      interval: daily
    groups:
      terraform-local-exec:
        patterns:
          - "*"
