---
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token-secret
        key: api-token
        optional: false
extraArgs:
  - --cloudflare-proxied

resources:
  limits:
    cpu: 50m
    memory: 50Mi

  requests:
    cpu: 10m
    memory: 50Mi
