---
# MegaLinter Config: https://oxsecurity.github.io/megalinter/configuration

# General Settings
SHOW_ELAPSED_TIME: true
DISABLE_ERRORS: true

# Linter Enable/Disable
DISABLE:
  - COPYPASTE
  - SPELL
# Tool Specific Config
