# MegaLinter Config: https://oxsecurity.github.io/megalinter/configuration
---
APPLY_FIXES: none
DISABLE:
  - COPYPASTE
  - REPOSITORY
  - SPELL
DISABLE_ERRORS_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TFLINT
DISABLE_LINTERS:
  - JSON_V8R
  - TERRAFORM_KICS
  - TERRAFORM_CHECKOV
  - YAML_V8R
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
