---
# MegaLinter Config: https://oxsecurity.github.io/megalinter/configuration
# General Settings
SHOW_ELAPSED_TIME: true

# Linter Enable/Disable
DISABLE:
  - COPYPASTE
  - SPELL
DISABLE_LINTERS:
  - TERRAFORM_KICS
DISABLE_ERRORS_LINTERS:
  - TERRAFORM_CHECKOV
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TFLINT
  - REPOSITORY_TRIVY
  - REPOSITORY_KICS
# Tool Specific Config
