---
# MegaLinter Config: https://oxsecurity.github.io/megalinter/configuration

# General Settings
SHOW_ELAPSED_TIME: true
SARIF_REPORTER: true

# Linter Enable/Disable
DISABLE_ERRORS: true
DISABLE:
  - COPYPASTE
  - SPELL
# Tool Specific Config
