# MegaLinter Config Ref: https://oxsecurity.github.io/megalinter/configuration
---
APPLY_FIXES: none
DISABLE:
  - COPYPASTE
  - REPOSITORY
  - SPELL
DISABLE_LINTERS:
  - TERRAFORM_KICS
DISABLE_ERRORS_LINTERS:
  - TERRAFORM_CHECKOV
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TFLINT
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
