---
# ref: https://terraform-docs.io/user-guide/configuration

formatter: markdown

header-from: terraform.tf

output:
  file: README.md
  mode: replace
  template: |
    {{ .Content }}

settings:
  anchor: false
  html: false
  hide-empty: true
