default_provider = "onepass"

[providers.onepass]
type = "1password"
vault = "Seeding"

[secrets.PINACT_GITHUB_TOKEN]
value = "GitHub-PAT-vyas-n/token"
[secrets.MISE_GITHUB_TOKEN]
value = "GitHub-PAT-vyas-n/token"
