---
# runnerdeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-test-runner-deployment
  namespace: actions-runner-controller
spec:
  replicas: 2
  template:
    spec:
      organization: vyas-proj
      labels:
        - k8s-runner-test
        - k8s-runner-test-1
      image: ghcr.io/vyas-proj/dev:latest
      imagePullPolicy: Always
