
[tasks.check]
run = ['prek run --all-files']

[tasks.setup]
depends = ['setup-ansible', 'setup-prek', 'setup-terraform', 'setup-uv']

[tasks.setup-ansible]
run = "ansible/requirements.yml"
sources = ['ansible/collections/**/*', 'ansible/requirements.yml']
outputs = ['{{env.HOME}}/.ansible/collections/ansible_collections']

[tasks.setup-prek]
run = "prek install"
sources = ['prek.toml']
outputs = ['.git/hooks/pre-commit']

[tasks.setup-terraform]
run = '''
    #!/usr/bin/env nu

    glob infra/**/*/.terraform.lock.hcl
    | path dirname
    | uniq
    | par-each { |tf_directory|
        terraform -chdir=($tf_directory) init --backend=false
    }
'''
sources = ['**/.terraform.lock.hcl', '**/terraform.tf']
outputs = ['**/.terraform']

[tasks.setup-uv]
run = "uv sync"
sources = ['pyproject.toml', 'uv.lock']
outputs = ['.venv']

[tasks.upgrade-deps]
alias = ["bump"]
depends = [
  'upgrade-dep-uv',
  'upgrade-dep-mise',
  'upgrade-dep-terraform',
  'upgrade-dep-pinact',
  'upgrade-dep-submodule',
]
run = '''
    #!/usr/bin/env nu

    mise latest terraform | save -f .terraform-version
    mise latest python | save -f .python-version
    mise install
'''

[tasks.upgrade-dep-pinact]
env.PINACT_GITHUB_TOKEN = { required = true }
run = "pinact run --update"
wait_for = ["upgrade-dep-mise"]

[tasks.upgrade-dep-uv]
run = "uv lock --upgrade"
wait_for = ["upgrade-dep-mise"]

[tasks.upgrade-dep-submodule]
run = "git submodule update --recursive --remote"

[tasks.upgrade-dep-terraform]
depends_post = ['docs']
run = '''
    #!/usr/bin/env nu

    glob infra/**/*/.terraform.lock.hcl
    | path dirname
    | uniq
    | par-each { |tf_directory|
        terraform -chdir=($tf_directory) init --upgrade
    }
'''
wait_for = ["upgrade-dep-mise"]

[tasks.upgrade-dep-mise]
env.MISE_GITHUB_TOKEN = { required = true }
run = "mise upgrade"

[tasks.docs]
depends_post = ['format']
run = '''
    #!/usr/bin/env nu

    glob infra/**/*.tf
    | path dirname
    | uniq
    | par-each {|tf_directory|
        terraform-docs markdown $tf_directory
    }
'''
sources = ['**/*.tf', '**/.terraform.lock.hcl']
outputs = ['**/README.md']

[tasks.format]
alias = ["fmt"]
depends = ['docs']
run = [
  "mise fmt",
  "just --fmt --unstable",
  "terraform fmt --recursive .",
  "prettier --write .",
  "markdown-table-formatter **/*.md",
]

[tasks.validate]
run = '''
    #!/usr/bin/env nu

    glob infra/**/*/.terraform.lock.hcl
    | path dirname
    | uniq
    | par-each {|tf_directory|
        terraform -chdir=($tf_directory) validate
    }
'''

[tasks.lint]
run = '''
    #!/usr/bin/env nu

    tflint --recursive --config=($env.PWD)/.tflint.hcl
'''

[tasks.ci]
depends = ['format', 'check', 'validate', 'lint']
