---
# https://artifacthub.io/packages/helm/argo/argo-cd
crds:
  install: true
configs:
  params:
    server.insecure: true
  repositories:
    docker-registry:
      url: registry-1.docker.io
      username: docker
      password: ""
      name: docker-registry
      enableOCI: "true"
      type: helm
    harbor-registry:
      url: harbor.wsbidev.net
      username: docker
      password: ""
      name: harbor-registry
      enableOCI: "true"
      type: helm
controller:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  # Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?orgId=1&refresh=10s&var-datasource=default&var-cluster=&var-namespace=argo-cd&var-type=All&var-workload=argo-cd-argocd-application-controller&from=now-30d&to=now
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
      ephemeral-storage: 128Mi
applicationSet:
  replicaCount: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  # Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?orgId=1&refresh=10s&var-datasource=default&var-cluster=&var-namespace=argo-cd&var-type=All&var-workload=argo-cd-argocd-applicationset-controller&from=now-30d&to=now
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
      ephemeral-storage: 128Mi
dex:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  # Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?orgId=1&refresh=10s&var-datasource=default&var-cluster=&var-namespace=argo-cd&var-type=All&var-workload=argo-cd-argocd-dex-server&from=now-30d&to=now
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi
      ephemeral-storage: 128Mi
notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  # Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?orgId=1&refresh=10s&var-datasource=default&var-cluster=&var-namespace=argo-cd&var-type=All&var-workload=argo-cd-argocd-notifications-controller&from=now-30d&to=now
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
      ephemeral-storage: 128Mi
  bots:
    slack:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 128Mi
redis:
  # Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?orgId=1&refresh=10s&var-datasource=default&var-cluster=&var-namespace=argo-cd&var-type=All&var-workload=argo-cd-argocd-redis&from=now-30d&to=now
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 16Mi
      ephemeral-storage: 128Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 16Mi
        ephemeral-storage: 128Mi
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  # Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?orgId=1&refresh=10s&var-datasource=default&var-cluster=&var-namespace=argo-cd&var-type=All&var-workload=argo-cd-argocd-repo-server&from=now-30d&to=now
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 128Mi
      ephemeral-storage: 128Mi
server:
  autoscaling:
    enabled: true
    minReplicas: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  ingress:
    enabled: true
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: zerossl-prod
    hostname: argo-cd.needham.wsbidev.net
    ingressClassName: cilium
  # Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?orgId=1&refresh=10s&var-datasource=default&var-cluster=&var-namespace=argo-cd&var-type=All&var-workload=argo-cd-argocd-server&from=now-30d&to=now
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
      ephemeral-storage: 128Mi
  extensions:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 64Mi
        ephemeral-storage: 128Mi
