---
# Vertical Pod Autoscaler Ref: https://artifacthub.io/packages/helm/cowboysysop/vertical-pod-autoscaler
admissionController:
  metrics:
    serviceMonitor:
      enabled: true
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
      ephemeral-storage: 128Mi
recommender:
  metrics:
    serviceMonitor:
      enabled: true
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi
      ephemeral-storage: 128Mi
updater:
  metrics:
    serviceMonitor:
      enabled: true
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi
      ephemeral-storage: 128Mi
