---
service:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "traefik-loadbalancer"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "true"
resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "300m"
    memory: "150Mi"
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
