---
services:
  whatsupdocker:
    image: docker.io/getwud/wud:8.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

      - datastore:/store
    ports:
      - 3000
    # healthcheck:
    #   test: curl --fail http://localhost:${WUD_SERVER_PORT:-3000}/health || exit 1
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s
    labels:
      # Homepage config
      # ref: https://gethomepage.dev/configs/docker/#automatic-service-discovery
      homepage.group: Docker Containers
      homepage.name: What's up Docker?
      homepage.icon: sh-whats-up-docker.svg
      homepage.href: https://whatsupdocker.tail5c72f1.ts.net
      homepage.siteMonitor: https://whatsupdocker.tail5c72f1.ts.net
      homepage.widget.type: whatsupdocker
      homepage.widget.url: https://whatsupdocker.tail5c72f1.ts.net

      # Tsdproxy config
      # ref: https://almeidapaulopt.github.io/tsdproxy/docs/docker
      tsdproxy.enable: true
      tsdproxy.name: whatsupdocker
      tsdproxy.container_port: 3000
    restart: unless-stopped

volumes:
  datastore:
