---
services:
  whatsupdocker:
    image: docker.io/getwud/wud:8.1.1
    volumes:
      # Mounted as read-only
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - datastore:/store

      # Get localtime zone from host
      # ref: https://getwud.github.io/wud/#/configuration/timezone
      - /etc/localtime:/etc/localtime:ro
    environment:
      WUD_SERVER_PORT: ${WUD_SERVER_PORT:-3000}
    ports:
      - ${WUD_SERVER_PORT:-3000}:${WUD_SERVER_PORT:-3000}
    healthcheck:
      test: curl --fail http://localhost:${WUD_SERVER_PORT:-3000}/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      # Homepage config
      # ref: https://gethomepage.dev/configs/docker/#automatic-service-discovery
      homepage.group: Docker Containers
      homepage.name: What's up Docker?
      homepage.icon: sh-wud.svg
      homepage.href: https://whatsupdocker.tail5c72f1.ts.net
      homepage.widget.type: whatsupdocker
      homepage.widget.url: http://truenas:4000

      # Tsdproxy config
      # ref: https://almeidapaulopt.github.io/tsdproxy/docs/docker
      tsdproxy.enable: true
      tsdproxy.name: whatsupdocker
      tsdproxy.autodetect: false
      tsdproxy.container_port: ${WUD_SERVER_PORT:-3000}

      # Whats up docker config
      wud.tag.include: ^v?\d+\.\d+\.\d+$$
    restart: unless-stopped

volumes:
  datastore:
