---
# Kyverno Helm Values Ref: https://artifacthub.io/packages/helm/kyverno/kyverno
grafana:
  enabled: true

# https://kyverno.io/docs/installation/methods/#high-availability
admissionController:
  replicas: 3
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  serviceMonitor:
    enabled: true
  container:
    # Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?var-datasource=default&var-cluster=&var-namespace=kyverno&var-workload=kyverno-admission-controller&var-type=deployment&orgId=1&refresh=10s&from=now-30d&to=now
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 128Mi

backgroundController:
  replicas: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  serviceMonitor:
    enabled: true
  # Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?var-datasource=default&var-cluster=&var-namespace=kyverno&var-workload=kyverno-background-controller&var-type=deployment&orgId=1&refresh=10s&from=now-30d&to=now
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
      ephemeral-storage: 128Mi

cleanupController:
  replicas: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  serviceMonitor:
    enabled: true
  # Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?var-datasource=default&var-cluster=&var-namespace=kyverno&var-workload=kyverno-cleanup-controller&var-type=deployment&orgId=1&refresh=10s&from=now-30d&to=now
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
      ephemeral-storage: 128Mi

reportsController:
  replicas: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  serviceMonitor:
    enabled: true
  # Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?var-datasource=default&var-cluster=&var-namespace=kyverno&var-workload=kyverno-reports-controller&var-type=deployment&orgId=1&refresh=10s&from=now-30d&to=now
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 128Mi
