# Config: https://github.com/k0sproject/k0sctl#configuration-file
---
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
    - role: controller+worker
      ssh:
        address: 45.32.195.235
        user: vyas
        port: 22
        keyPath: /Users/vnellutla/.ssh/vyas-workbook-8.pem
    - role: controller+worker
      ssh:
        address: 216.128.139.33
        user: vyas
        port: 22
        keyPath: /Users/vnellutla/.ssh/vyas-workbook-8.pem
    - role: controller+worker
      ssh:
        address: 207.148.3.245
        user: vyas
        port: 22
        keyPath: /Users/vnellutla/.ssh/vyas-workbook-8.pem
  k0s:
    version: 1.25.2+k0s.0
    dynamicConfig: false
    config:
      # Config: https://docs.k0sproject.io/v1.25.2+k0s.0/configuration/#configuration-file-reference
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
        # extensions:
        #   storage:
        #     type: openebs_local_storage
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          kubeProxy:
            disabled: false
            mode: iptables
          podCIDR: 10.244.0.0/16
          provider: calico
          serviceCIDR: 10.96.0.0/12
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: true
