---
# cert-manager Helm Values Ref: https://artifacthub.io/packages/helm/cert-manager/cert-manager
# yaml-language-server: $schema=https://github.com/cert-manager/cert-manager/raw/refs/heads/master/deploy/charts/cert-manager/values.schema.json
crds:
  enabled: true
prometheus:
  enabled: true
  servicemonitor:
    enabled: true

livenessProbe:
  enabled: true
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

webhook:
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 30m
      memory: 32Mi

cainjector:
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

startupapicheck:
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 32Mi
