---
services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.3.0
    container_name: dockerproxy
    environment:
      # ref: https://github.com/Tecnativa/docker-socket-proxy?tab=readme-ov-file#access-revoked-by-default
      # Allow access to viewing containers
      CONTAINERS: 1
      # Allow access to viewing services (necessary when using Docker Swarm)
      # SERVICES: 1
      # Allow access to viewing tasks (necessary when using Docker Swarm)
      # TASKS: 1
      # Disallow any POST operations (effectively read-only)
      POST: 0
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      # Mounted as read-only
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.13
    container_name: homepage
    ports:
      - 3000
    volumes:
      - ${DEPLOY_HOMEPAGE_CONFIG_DIR}:/app/config # Make sure your local config directory exists
    labels:
      # Homepage config
      # ref: https://gethomepage.dev/configs/docker/#automatic-service-discovery
      homepage.group: Docker Containers
      homepage.name: Homepage
      homepage.icon: sh-homepage
      homepage.href: https://homepage.tail5c72f1.ts.net
      homepage.siteMonitor: https://homepage.tail5c72f1.ts.net
      homepage.ping: homepage.tail5c72f1.ts.net

      # Tsdproxy config
      # ref: https://almeidapaulopt.github.io/tsdproxy/docs/docker
      tsdproxy.enable: true
      tsdproxy.name: homepage
      tsdproxy.container_port: 3000
    restart: unless-stopped
