---
injector.enabled: false
server:
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m
  ingress:
    enabled: true
    hosts:
      - host: vault.vyas-n.com
        paths: []
  standalone:
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "raft" {
        path = "/vault/data"
        node_id = "raft_node_1"
      }
