---
# https://artifacthub.io/packages/helm/grafana/loki
loki:
  auth_enabled: false
  storage:
    bucketNames:
      chunks: loki-bucket
      ruler: loki-bucket
      admin: loki-bucket
    s3:
      s3: s3://loki-bucket
      region: ${S3_LOKI_REGION}
      endpoint: ${S3_LOKI_HOST}
      accessKeyId: ${S3_LOKI_ACCESS_KEY_ID}
      secretAccessKey: ${S3_LOKI_SECRET_ACCESS_KEY}
      s3ForcePathStyle: true
      insecure: true

backend:
  autoscaling:
    enabled: true
  extraArgs:
    - "-config.expand-env=true"
  extraEnv: &extraEnv
    - name: S3_LOKI_HOST
      valueFrom:
        configMapKeyRef:
          name: loki-bucket
          key: BUCKET_HOST
    - name: S3_LOKI_REGION
      valueFrom:
        configMapKeyRef:
          name: loki-bucket
          key: BUCKET_REGION
    - name: S3_LOKI_HOST
      valueFrom:
        configMapKeyRef:
          name: loki-bucket
          key: BUCKET_HOST
    - name: S3_LOKI_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: loki-bucket
          key: AWS_ACCESS_KEY_ID
    - name: S3_LOKI_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-bucket
          key: AWS_SECRET_ACCESS_KEY
  resources:
    limits:
      cpu: 2000m
      memory: 8192Mi
    requests:
      cpu: 500m
      memory: 4096Mi
      ephemeral-storage: 128Mi

gateway:
  autoscaling:
    enabled: true
  extraArgs:
    - "-config.expand-env=true"
  extraEnv: *extraEnv
  resources:
    limits:
      cpu: 2000m
      memory: 8192Mi
    requests:
      cpu: 500m
      memory: 4096Mi
      ephemeral-storage: 128Mi

write:
  autoscaling:
    enabled: true
  extraArgs:
    - "-config.expand-env=true"
  extraEnv: *extraEnv
  resources:
    limits:
      cpu: 2000m
      memory: 8192Mi
    requests:
      cpu: 500m
      memory: 4096Mi
      ephemeral-storage: 128Mi

read:
  autoscaling:
    enabled: true
  extraArgs:
    - "-config.expand-env=true"
  extraEnv: *extraEnv
  resources:
    limits:
      cpu: 2000m
      memory: 8192Mi
    requests:
      cpu: 500m
      memory: 4096Mi
      ephemeral-storage: 128Mi
