---
# Ansible Playbook Refs:
# - Syntax: https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html#playbook-syntax
# - Collection Index: https://docs.ansible.com/ansible/latest/collections/index.html
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/schemas/main/f/ansible.json#/$defs/playbook
- name: Deploy Traefik
  hosts: truenas
  collections: []
  tasks:
    - name: Creates directory & intermediate directories
      ansible.builtin.file:
        path: "{{ item.name }}"
        state: directory
        owner: admin
        group: root
        # Set directories as 0770 & files as 0660
        # ref: https://stackoverflow.com/a/29793833
        mode: u=rwX,g=rwX
      loop:
        - name: /mnt/app1/apps/dockge/stacks/traefik
        - name: /mnt/app1/apps/traefik/config
    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: admin
        group: root
        # Set directories as 0770 & files as 0660
        # ref: https://stackoverflow.com/a/29793833
        mode: u=rwX,g=rwX
      loop:
        - src: compose.yaml
          dest: /mnt/app1/apps/dockge/stacks/traefik/compose.yaml
        - src: config/traefik.yml
          dest: /mnt/app1/apps/traefik/config/traefik.yml
