---
# Ansible Inventory Ref: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/schemas/main/f/ansible-inventory.json
all:
  vars:
    ansible_user: vyas
  children:
    proxmox:
      vars:
        # Workaround for an ssh issue with the default search domain on my laptop
        # ref: https://stackoverflow.com/a/77461212
        host_domain: hosts.vyas-n.dev
        ansible_host: "{{inventory_hostname_short}}.{{host_domain}}"

        # TODO: add local user vyas to avoid direct root connection
        ansible_user: root
      hosts:
        proxmox-0:
          has_amd_gpu: true
        proxmox-1:
          has_amd_gpu: true
        proxmox-2:
          has_amd_gpu: true
    vms:
      vars:
        # Workaround for an ssh issue with the default search domain on my laptop
        # ref: https://stackoverflow.com/a/77461212
        host_domain: vms.vyas-n.dev
        ansible_host: "{{inventory_hostname_short}}.{{host_domain}}"

      children:
        docker_servers:
          hosts:
            docker-server-0:
            docker-server-1:
        k8s:
          hosts:
            k8s-ctr-0:
            k8s-ctr-1:
            k8s-ctr-2:
            k8s-wkr-0:
            k8s-wkr-1:
            k8s-wkr-2:
            k8s-wkr-3:
      hosts:
        # gaming-vm-win11:
        #   # Must Setup Windows host with ssh:
        #   #   - https://docs.ansible.com/ansible/latest/os_guide/windows_ssh.html#ssh-setup
        #   #   - https://docs.ansible.com/ansible/latest/os_guide/windows_ssh.html#key-authentication
        #   ansible_host: gaming-vm-win11.hosts.vyas-n.dev
        #   ansible_shell_type: powershell
        #   ansible_connection: ssh
        gaming-vm-bazzite:
  hosts:
    truenas:
      # TODO: fix DNS resolver so that truenas correctly resolves
      ansible_host: truenas.hosts.vyas-n.dev
