---
- name: Copy Tailscale kernel parameters
  ansible.builtin.copy:
    src: "{{ item.name }}"
    dest: /{{ item.name }}
    owner: root
    group: root
    mode: "0644"
  loop:
    - name: etc/sysctl.d/99-tailscale.conf
  notify:
    - Add kernel parameters
- name: Tailscale GPG Key
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    owner: root
    group: root
    mode: "0644"
- name: Tailscale APT Repo
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list
    dest: /etc/apt/sources.list.d/tailscale.list
    owner: root
    group: root
    mode: "0644"
- name: Install Tailscale
  ansible.builtin.apt:
    package:
      - tailscale
    state: present
    update_cache: true
# TODO: unattended install of tailscale:
# tailscale up --advertise-exit-node --advertise-routes=192.168.2.0/24 --auth-key=<generate-auth-key>

# TODO: auto approve tailscale node
