---
services:
  uptime_kuma:
    image: docker.io/louislam/uptime-kuma:1.23.16
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/app/data
    ports:
      - 3001:3001
    labels:
      # Homepage config
      # ref: https://gethomepage.dev/configs/docker/#automatic-service-discovery
      homepage.group: Docker Containers
      homepage.name: Uptime-Kuma
      homepage.icon: sh-uptime-kuma.svg
      homepage.href: https://uptime-kuma.tail5c72f1.ts.net

      # Tsdproxy config
      # ref: https://almeidapaulopt.github.io/tsdproxy/docs/docker
      tsdproxy.enable: true
      tsdproxy.name: uptime-kuma
      tsdproxy.container_port: 3001

      # Whats up docker config
      wud.tag.include: ^v?\d+\.\d+\.\d+$$
    restart: unless-stopped

volumes:
  datadir:
