---
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:1.4.7
    configs:
      - source: tsdproxy.yaml
        target: /config/tsdproxy.yaml
        mode: 0440
    ports:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
    labels:
      # Homepage config
      # ref: https://gethomepage.dev/configs/docker/#automatic-service-discovery
      homepage.group: Docker Containers
      homepage.name: TSDProxy
      homepage.icon: sh-tailscale-light.svg
      homepage.href: https://tsdproxy.tail5c72f1.ts.net

      # Tsdproxy config
      # ref: https://almeidapaulopt.github.io/tsdproxy/docs/docker
      tsdproxy.enable: true
      tsdproxy.name: tsdproxy
      tsdproxy.container_port: 8080
      tsdproxy.dash.icon: sh/tailscale-light
    restart: unless-stopped
configs:
  tsdproxy.yaml:
    content: |
      defaultproxyprovider: default
      docker:
        local: # name of the docker provider
          host: unix:///var/run/docker.sock # host of the docker socket or daemon
          targethostname: truenas.hosts.vyas-n.dev # hostname or IP of docker server
          defaultproxyprovider: default # name of which proxy provider to use
      tailscale:
        providers:
          # name of the provider
          default:
            # ref {{ lookup('community.general.onepassword', 'tailscale-authkey-tsdproxy-truenas', field='credential', vault='Private') }}
            authkey: ${TAILSCALE_AUTHKEY}
            # authkeyfile: "" # use this to load authkey from file. If this is defined, Authkey is ignored
            controlurl: https://controlplane.tailscale.com # use this to override the default control URL
        datadir: /data/
      http:
        hostname: 0.0.0.0
        port: 8080
      log:
        level: info # set logging level info, error or trace
        json: false # set to true to enable json logging
      proxyaccesslog: true # set to true to enable container access log

volumes:
  datadir:
