---
# External Secrets Ref: https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets
# yaml-language-server: $schema=https://github.com/external-secrets/external-secrets/raw/refs/heads/main/deploy/charts/external-secrets/values.schema.json
installCRDs: true

serviceMonitor:
  enabled: true
# Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?var-datasource=default&var-cluster=&var-namespace=external-secrets&var-workload=external-secrets&var-type=All&orgId=1&refresh=10s&from=now-30d&to=now
resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 128Mi

webhook:
  serviceMonitor:
    enabled: true
  # Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?var-datasource=default&var-cluster=&var-namespace=external-secrets&var-workload=external-secrets-webhook&var-type=All&orgId=1&refresh=10s&from=now-30d&to=now
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
      ephemeral-storage: 128Mi

certController:
  serviceMonitor:
    enabled: true
  # Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?var-datasource=default&var-cluster=&var-namespace=external-secrets&var-workload=external-secrets-cert-controller&var-type=All&orgId=1&refresh=10s&from=now-30d&to=now
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 30m
      memory: 128Mi
      ephemeral-storage: 128Mi
