---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dnsutils
  namespace: default
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      containers:
        - name: dnsutils
          image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
          command:
            - sleep
            - "infinity"
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
