---
# https://artifacthub.io/packages/helm/argo/argo-cd
crds:
  install: true
configs:
  params:
    server.insecure: true
  repositories:
    docker-registry:
      url: registry-1.docker.io
      username: docker
      password: ""
      name: docker-registry
      enableOCI: "true"
      type: helm
controller:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
      ephemeral-storage: 128Mi
applicationSet:
  replicaCount: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
      ephemeral-storage: 128Mi
dex:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 32Mi
      ephemeral-storage: 128Mi
notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
      ephemeral-storage: 128Mi
  bots:
    slack:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 128Mi
redis:
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 16Mi
      ephemeral-storage: 128Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 16Mi
        ephemeral-storage: 128Mi
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 128Mi
      ephemeral-storage: 128Mi
server:
  autoscaling:
    enabled: true
    minReplicas: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  ingress:
    enabled: true
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: zerossl-prod
    hostname: argo-cd.homezone-v1.vyas-n.dev
    ingressClassName: cilium
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
      ephemeral-storage: 128Mi
  extensions:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 64Mi
        ephemeral-storage: 128Mi
