---
# k0sctl config
# ref: https://github.com/k0sproject/k0sctl?tab=readme-ov-file#configuration-file
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: homezone-v1
  user: homezone-admin
spec:
  hosts:
    - role: controller
      installFlags: &controllerinstallflags
        - --labels
        - topology.kubernetes.io/region=homelab
        - --labels
        - topology.kubernetes.io/zone=vlan1
        # Monitoring k8s Control Plane: https://docs.k0sproject.io/stable/system-monitoring/#system-components-monitoring
        - --enable-metrics-scraper
      openSSH:
        address: k8s-ctr-0
        # user: vyas
    - role: controller
      installFlags: *controllerinstallflags
      openSSH:
        address: k8s-ctr-1
        # user: vyas
    - role: controller
      installFlags: *controllerinstallflags
      openSSH:
        address: k8s-ctr-2
        # user: vyas
    - role: worker
      installFlags: &workerinstallflags
        - --labels
        - topology.kubernetes.io/region=homelab
        - --labels
        - topology.kubernetes.io/zone=vlan1
      openSSH:
        address: k8s-wkr-0
        # user: vyas
    - role: worker
      installFlags: *workerinstallflags
      openSSH:
        address: k8s-wkr-1
        # user: vyas
    - role: worker
      installFlags: *workerinstallflags
      openSSH:
        address: k8s-wkr-2
        # user: vyas
    # - role: worker
    #   installFlags: *workerinstallflags
    #   openSSH:
    #     address: k8s-wkr-3
    #     user: vyas
  k0s:
    # releases: https://github.com/k0sproject/k0s/releases/latest
    version: v1.34.3+k0s.0
    config:
      # k0s config
      # ref: https://docs.k0sproject.io/stable/configuration/#configuration-file-reference
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: homezone-v1
      spec:
        api:
          address: 192.168.2.8
          k0sApiPort: 9443
          port: 6443
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          kubeProxy:
            disabled: true
          nodeLocalLoadBalancing:
            enabled: true
            type: EnvoyProxy
          controlPlaneLoadBalancing:
            enabled: false
            type: Keepalived
            keepalived:
              vrrpInstances:
                - virtualIPs: ["192.168.2.8/32"]
                  authPass: fd3sahds
          provider: custom
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          dualStack:
            enabled: false
            # IPv6podCIDR: fd00::/108
            # IPv6serviceCIDR: fd01::/108
        storage:
          type: etcd
        telemetry:
          enabled: true
