#cloud-config
# Cloud config Refs:
# - Base Config: https://cloudinit.readthedocs.io/en/latest/topics/base_config_reference.html
# - Module Config: https://cloudinit.readthedocs.io/en/latest/topics/modules.html
# - Examples: https://cloudinit.readthedocs.io/en/latest/topics/examples.html

packages:
  - fish
  - curl
  - ca-certificates
  - apt-transport-https
package_update: true
package_upgrade: true
package_reboot_if_required: true

users:
  - name: vyas
    gecos: Vyas
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_import_id:
      - gh:vyas-n
