---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.13
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /mnt/data1/apps/homepage/config:/app/config # Make sure your local config directory exists
