---
- name: Creates directory & intermediate directories
  ansible.builtin.file:
    path: "{{ item.name }}"
    state: directory
    owner: admin
    group: root
    # Set directories as 0770 & files as 0660
    # ref: https://stackoverflow.com/a/29793833
    mode: u=rwX,g=rwX
  loop:
    - name: /mnt/app1/apps/dockge/stacks/homepage
    - name: /mnt/app1/apps/homepage/config
- name: Template files (explicitly skip directories in order to use the 'src' attribute)
  ansible.builtin.template:
    src: "{{ item.src }}"
    # Your template files should be stored with a .j2 file extension,
    # but should not be deployed with it. splitext|first removes it.
    dest: /mnt/app1/apps/homepage/config/{{ item.path | splitext | first }}
    owner: admin
    group: root
    # Set directories as 0770 & files as 0660
    # ref: https://stackoverflow.com/a/29793833
    mode: u=rwX,g=rwX
  loop: "{{ lookup('community.general.filetree', 'templates/config') }}"
  when: item.state == 'file'
- name: Copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: admin
    group: root
    # Set directories as 0770 & files as 0660
    # ref: https://stackoverflow.com/a/29793833
    mode: u=rwX,g=rwX
  loop:
    - src: compose.yaml
      dest: /mnt/app1/apps/dockge/stacks/homepage/compose.yaml
