# https://artifacthub.io/packages/helm/cilium/cilium
---
# resources:
#   limits:
#     cpu: 4000m
#     memory: 4Gi
#   requests:
#     cpu: 100m
#     memory: 512Mi
# operator:
#   resources:
#     limits:
#       cpu: 1000m
#       memory: 1Gi
#     requests:
#       cpu: 100m
#       memory: 128Mi
hubble:
  ui:
    enabled: true
  relay:
    enabled: true
ipv6:
  enabled: true
