---
# Kyverno Helm Values Ref: https://artifacthub.io/packages/helm/kyverno/kyverno
grafana:
  enabled: true

# https://kyverno.io/docs/installation/methods/#high-availability
admissionController:
  serviceMonitor:
    enabled: true
  container:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 128Mi

backgroundController:
  serviceMonitor:
    enabled: true
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
      ephemeral-storage: 128Mi

cleanupController:
  serviceMonitor:
    enabled: true
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
      ephemeral-storage: 128Mi

reportsController:
  serviceMonitor:
    enabled: true
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 128Mi
