---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

# For icons, use `sh-<icon>`: https://selfh.st/icons/

- Network:
    - Unifi (Vyas's Home Network):
        href: https://unifi.ui.com/consoles/0CEA144D1F27000000000871A9680000000008E4BFA800000000671C5D48:243437069/network/default/dashboard
        siteMonitor: https://192.168.2.1
        ping: 192.168.2.1
        icon: sh-ubiquiti-unifi.svg
        widget:
          type: unifi
          url: https://192.168.2.1
          username: "${UNIFI_GATEWAY_USERNAME}"
          password: "${UNIFI_GATEWAY_PASSWORD}"
    - HomeLab Subnet Router (truenas):
        href: https://login.tailscale.com/admin/machines/100.96.207.121
        ping: truenas.hosts.vyas-n.dev
        icon: sh-tailscale-light.svg
        fields: ["last_seen", "expires"]
        widget:
          type: tailscale
          deviceid: ncCBFBRUH811CNTRL
          key: "${TAILSCALE_API_TOKEN}"
    - HomeLab Subnet Router (proxmox-0):
        href: https://login.tailscale.com/admin/machines/100.70.202.28
        ping: proxmox-0.hosts.vyas-n.dev
        icon: sh-tailscale-light.svg
        fields: ["last_seen", "expires"]
        widget:
          type: tailscale
          deviceid: nmYhQDWrtH11CNTRL
          key: "${TAILSCALE_API_TOKEN}"
    - HomeLab Subnet Router (proxmox-1):
        href: https://login.tailscale.com/admin/machines/100.113.99.101
        ping: proxmox-1.hosts.vyas-n.dev
        icon: sh-tailscale-light.svg
        fields: ["last_seen", "expires"]
        widget:
          type: tailscale
          deviceid: nB1Phx2Gp311CNTRL
          key: "${TAILSCALE_API_TOKEN}"
    - HomeLab Subnet Router (proxmox-2):
        href: https://login.tailscale.com/admin/machines/100.125.129.4
        ping: proxmox-2.hosts.vyas-n.dev
        icon: sh-tailscale-light.svg
        fields: ["last_seen", "expires"]
        widget:
          type: tailscale
          deviceid: nhu7WZpxRm11CNTRL
          key: "${TAILSCALE_API_TOKEN}"
- Management:
    - TrueNAS JetKVM:
        href: http://192.168.2.158
        siteMonitor: http://192.168.2.158
        ping: 192.168.2.158
        icon: sh-jetkvm.svg
    - Proxmox-0 JetKVM:
        href: http://jetkvm.proxmox-0.hosts.vyas-n.dev
        siteMonitor: http://jetkvm.proxmox-0.hosts.vyas-n.dev
        ping: jetkvm.proxmox-0.hosts.vyas-n.dev
        icon: sh-jetkvm.svg
    - Proxmox-1 IPMI:
        href: https://proxmox-1-ipmi.hosts.vyas-n.dev
        siteMonitor: https://proxmox-1-ipmi.hosts.vyas-n.dev
        ping: proxmox-1-ipmi.hosts.vyas-n.dev
        icon: sh-asrock.svg
    - Sunshine (Anshula-Laptop):
        href: https://anshula-laptop.tail5c72f1.ts.net:47990
        icon: sh-sunshine.svg
    - Sunshine (gaming-vm-bazzite):
        href: https://gaming-vm-bazzite.tail5c72f1.ts.net:47990
        icon: sh-sunshine.svg

- Compute:
    - TrueNAS:
        href: https://truenas.hosts.vyas-n.dev
        siteMonitor: https://truenas.hosts.vyas-n.dev
        ping: truenas.hosts.vyas-n.dev
        icon: sh-truenas-scale.svg
    - Proxmox-0:
        href: https://proxmox-0.hosts.vyas-n.dev
        siteMonitor: https://proxmox-0.hosts.vyas-n.dev
        ping: proxmox-0.hosts.vyas-n.dev
        icon: sh-proxmox.svg
        widget:
          type: proxmox
          url: https://proxmox-0.hosts.vyas-n.dev
          username: ${PROXMOX_TOKEN_ID}
          password: ${PROXMOX_API_TOKEN}
          node: proxmox-0
    - Proxmox-1:
        href: https://proxmox-1.hosts.vyas-n.dev
        siteMonitor: https://proxmox-1.hosts.vyas-n.dev
        ping: proxmox-1.hosts.vyas-n.dev
        icon: sh-proxmox.svg
        widget:
          type: proxmox
          url: https://proxmox-1.hosts.vyas-n.dev
          username: ${PROXMOX_TOKEN_ID}
          password: ${PROXMOX_API_TOKEN}
          node: proxmox-1
    - Proxmox-2:
        href: https://proxmox-2.hosts.vyas-n.dev
        siteMonitor: https://proxmox-2.hosts.vyas-n.dev
        ping: proxmox-2.hosts.vyas-n.dev
        icon: sh-proxmox.svg
        widget:
          type: proxmox
          url: https://proxmox-2.hosts.vyas-n.dev
          username: ${PROXMOX_TOKEN_ID}
          password: ${PROXMOX_API_TOKEN}
          node: proxmox-2

- Docker Containers: []
