---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/service-widgets

- openmeteo:
    units: imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1

# TODO: Widget seems to be broken
# - unifi_console:
#     url: http://192.168.2.1
#     username: ${UNIFI_GATEWAY_USERNAME}
#     password: ${UNIFI_GATEWAY_PASSWORD}

- resources:
    label: TrueNAS Resources
    expanded: true
    cpu: true
    memory: true
    cputemp: true
    uptime: true
