---
# Ansible Inventory Ref: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/schemas/main/f/ansible-inventory.json
all:
  children:
    proxmox:
      hosts:
        proxmox-0:
          has_amd_gpu: true
        proxmox-1:
          has_amd_gpu: true
        proxmox-2:
          has_amd_gpu: true
    vms:
      children:
        k8s:
          hosts:
            k8s-ctr-0:
            k8s-ctr-1:
            k8s-ctr-2:
            k8s-wkr-0:
            k8s-wkr-1:
      hosts:
        # gaming-vm-win11:
        #   # Must Setup Windows host with ssh:
        #   #   - https://docs.ansible.com/ansible/latest/os_guide/windows_ssh.html#ssh-setup
        #   #   - https://docs.ansible.com/ansible/latest/os_guide/windows_ssh.html#key-authentication
        #   ansible_host: gaming-vm-win11.hosts.vyas-n.dev
        #   ansible_shell_type: powershell
        #   ansible_connection: ssh
        docker-server:
  hosts:
    raspberrypi-0:
    raspberrypi-desktop-0:
    truenas:
