---
# Ansible Inventory Ref: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/schemas/main/f/ansible-inventory.json
all:
  children:
    proxmox:
      hosts:
        proxmox_1:
          ansible_host: proxmox-1.hosts.vyas-n.dev
        proxmox_2:
          ansible_host: proxmox-2.hosts.vyas-n.dev
  hosts:
    truenas:
      ansible_host: truenas.hosts.vyas-n.dev
