#!/usr/bin/env -S uv run ansible-galaxy collection install --force -r

collections:
  # https://galaxy.ansible.com/ui/repo/published/community/general/
  - name: community.general
    version: 12.4.0
  - name: community.docker
    version: 5.0.6
  - name: ansible.posix
    version: 2.1.0
  # TODO: move the ansible collections into a separate repo
  # TODO: setup molecule testing for each role in collections
  - name: ./collections/ansible_collections/vyas
    type: subdirs
  - name: ansible.windows
    version: 3.3.0
  - name: artis3n.tailscale
    version: 1.2.1
