---
collections:
  - name: community.general
    version: 10.4.0
  - name: ansible.posix
    version: 2.0.0
  - name: ./collections/ansible_collections/vyas
    type: subdirs
  - name: ansible.windows
    version: 2.7.0
