---
services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.3.0
    container_name: dockerproxy
    environment:
      # ref: https://github.com/Tecnativa/docker-socket-proxy?tab=readme-ov-file#access-revoked-by-default
      # Allow access to viewing containers
      CONTAINERS: 1
      # Allow access to viewing services (necessary when using Docker Swarm)
      # SERVICES: 1
      # Allow access to viewing tasks (necessary when using Docker Swarm)
      # TASKS: 1
      # Disallow any POST operations (effectively read-only)
      POST: 0
    ports:
      - 2375
    volumes:
      # Mounted as read-only
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:v1.3.2
    container_name: homepage
    ports:
      - 3000:3000
    environment:
      SAMPLE: try-again-3
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
    configs:
      - source: bookmarks.yaml
        target: /app/config/bookmarks.yaml
      - source: custom.css
        target: /app/config/custom.css
      - source: custom.js
        target: /app/config/custom.js
      - source: docker.yaml
        target: /app/config/docker.yaml
      - source: kubernetes.yaml
        target: /app/config/kubernetes.yaml
      - source: services.yaml
        target: /app/config/services.yaml
      - source: settings.yaml
        target: /app/config/settings.yaml
      - source: widgets.yaml
        target: /app/config/widgets.yaml

    labels:
      # Homepage config
      # ref: https://gethomepage.dev/configs/docker/#automatic-service-discovery
      homepage.group: Docker Containers
      homepage.name: Homepage
      homepage.icon: sh-homepage
      homepage.href: https://homepage.tail5c72f1.ts.net

      # Tsdproxy config
      # ref: https://almeidapaulopt.github.io/tsdproxy/docs/docker
      tsdproxy.enable: true
      tsdproxy.name: homepage
      tsdproxy.container_port: 3000
    restart: unless-stopped
configs:
  bookmarks.yaml:
    content: |
      ---
      # For configuration options and examples, please see:
      # https://gethomepage.dev/configs/bookmarks

      - SaaS Services:
        - Cloudflare:
          - href: https://dash.cloudflare.com
            icon: sh-cloudflare.svg
        - GitHub:
          - href: https://github.com
            icon: sh-github-light.svg
        - Grafana:
          - href: https://vyasn.grafana.net
            icon: sh-grafana.svg
        - Tailscale:
          - href: https://login.tailscale.com
            icon: sh-tailscale-light.svg
        - Terraform Cloud:
          - href: https://app.terraform.io
            icon: sh-hashicorp-terraform.svg

      - Tracking / Stats:
        - YNAB:
          - href: https://https://app.ynab.com
            icon: sh-ynab.svg
        - The StoryGraph:
          - href: https://app.thestorygraph.com

      - Developer Docs:
        - Homepage docs:
          - href: https://gethomepage.dev/widgets/
            icon: sh-homepage
        - Self-Hosted Icons:
          - href: https://selfh.st/icons/
            icon: sh-selfh-st.svg

      - Entertainment:
        - YouTube:
          - href: https://youtube.com
            icon: sh-youtube.svg
        - Twitch:
          - href: https://twitch.tv
            icon: sh-twitch.svg

      - Training:
        - A Cloud Guru:
          - href: https://learn.acloud.guru
  custom.css:
    content: |

  custom.js:
    content: |

  docker.yaml:
    content: |
      ---
      # For configuration options and examples, please see:
      # https://gethomepage.dev/configs/docker/

      truenas-docker:
        host: dockerproxy
        port: 2375

      # my-docker:
      #   socket: /var/run/docker.sock
  kubernetes.yaml:
    content: |
      ---
      # sample kubernetes config
  services.yaml:
    content: |
      ---
      # For configuration options and examples, please see:
      # https://gethomepage.dev/configs/services

      # For icons, use `sh-<icon>`: https://selfh.st/icons/

      - Network:
        - Unifi (Vyas's Home Network):
            href: https://unifi.ui.com/consoles/0CEA144D1F27000000000871A9680000000008E4BFA800000000671C5D48:243437069/network/default/dashboard
            siteMonitor: https://192.168.2.1
            ping: 192.168.2.1
            icon: sh-ubiquiti-unifi.svg
            widget:
              type: unifi
              url: https://192.168.2.1
              username: "${UNIFI_GATEWAY_USERNAME}"
              password: "${UNIFI_GATEWAY_PASSWORD}"
        - HomeLab Subnet Router (truenas):
            href: https://login.tailscale.com/admin/machines/100.96.207.121
            ping: truenas.hosts.vyas-n.dev
            icon: sh-tailscale-light.svg
            fields: ["last_seen", "expires"]
            widget:
              type: tailscale
              deviceid: ncCBFBRUH811CNTRL
              key: "${TAILSCALE_API_TOKEN}"
        - HomeLab Subnet Router (proxmox-0):
            href: https://login.tailscale.com/admin/machines/100.70.202.28
            ping: proxmox-0.hosts.vyas-n.dev
            icon: sh-tailscale-light.svg
            fields: ["last_seen", "expires"]
            widget:
              type: tailscale
              deviceid: nmYhQDWrtH11CNTRL
              key: "${TAILSCALE_API_TOKEN}"
        - HomeLab Subnet Router (proxmox-1):
            href: https://login.tailscale.com/admin/machines/100.113.99.101
            ping: proxmox-1.hosts.vyas-n.dev
            icon: sh-tailscale-light.svg
            fields: ["last_seen", "expires"]
            widget:
              type: tailscale
              deviceid: nB1Phx2Gp311CNTRL
              key: "${TAILSCALE_API_TOKEN}"
        - HomeLab Subnet Router (proxmox-2):
            href: https://login.tailscale.com/admin/machines/100.125.129.4
            ping: proxmox-2.hosts.vyas-n.dev
            icon: sh-tailscale-light.svg
            fields: ["last_seen", "expires"]
            widget:
              type: tailscale
              deviceid: nhu7WZpxRm11CNTRL
              key: "${TAILSCALE_API_TOKEN}"
      - Management:
        - TrueNAS JetKVM:
            href: http://192.168.2.158
            siteMonitor: http://192.168.2.158
            ping: 192.168.2.158
            icon: sh-jetkvm.svg
        - Proxmox-0 JetKVM:
            href: http://jetkvm.proxmox-0.hosts.vyas-n.dev
            siteMonitor: http://jetkvm.proxmox-0.hosts.vyas-n.dev
            ping: jetkvm.proxmox-0.hosts.vyas-n.dev
            icon: sh-jetkvm.svg
        - Proxmox-1 IPMI:
            href: https://proxmox-1-ipmi.hosts.vyas-n.dev
            siteMonitor: https://proxmox-1-ipmi.hosts.vyas-n.dev
            ping: proxmox-1-ipmi.hosts.vyas-n.dev
            icon: sh-asrock.svg
        - Sunshine (Anshula-Laptop):
            href: https://anshula-laptop.tail5c72f1.ts.net:47990
            icon: sh-sunshine.svg
        - Sunshine (gaming-vm-bazzite):
            href: https://gaming-vm-bazzite.tail5c72f1.ts.net:47990
            icon: sh-sunshine.svg

      - Compute:
        - TrueNAS:
            href: https://truenas.hosts.vyas-n.dev
            siteMonitor: https://truenas.hosts.vyas-n.dev
            ping: truenas.hosts.vyas-n.dev
            icon: sh-truenas-scale.svg
        - Proxmox-0:
            href: https://proxmox-0.hosts.vyas-n.dev
            siteMonitor: https://proxmox-0.hosts.vyas-n.dev
            ping: proxmox-0.hosts.vyas-n.dev
            icon: sh-proxmox.svg
            widget:
              type: proxmox
              url: https://proxmox-0.hosts.vyas-n.dev
              username: ${PROXMOX_TOKEN_ID}
              password: ${PROXMOX_API_TOKEN}
              node: proxmox-0
        - Proxmox-1:
            href: https://proxmox-1.hosts.vyas-n.dev
            siteMonitor: https://proxmox-1.hosts.vyas-n.dev
            ping: proxmox-1.hosts.vyas-n.dev
            icon: sh-proxmox.svg
            widget:
              type: proxmox
              url: https://proxmox-1.hosts.vyas-n.dev
              username: ${PROXMOX_TOKEN_ID}
              password: ${PROXMOX_API_TOKEN}
              node: proxmox-1
        - Proxmox-2:
            href: https://proxmox-2.hosts.vyas-n.dev
            siteMonitor: https://proxmox-2.hosts.vyas-n.dev
            ping: proxmox-2.hosts.vyas-n.dev
            icon: sh-proxmox.svg
            widget:
              type: proxmox
              url: https://proxmox-2.hosts.vyas-n.dev
              username: ${PROXMOX_TOKEN_ID}
              password: ${PROXMOX_API_TOKEN}
              node: proxmox-2

      - Docker Containers: []
  settings.yaml:
    content: |
      ---
      # For configuration options and examples, please see:
      # https://gethomepage.dev/configs/settings

      # Themeing
      theme: dark
      color: slate
      background:
        image: https://github.com/gethomepage/homepage/blob/a06964dd175fa798fa9189ba1ecd5766bbde543f/docs/assets/blossom_valley.jpg?raw=true

      headerStyle: clean

      quicklaunch:
        searchDescriptions: true
        showSearchSuggestions: true
        provider: duckduckgo

      # providers:
      #   openweathermap: openweathermapapikey
      #   weatherapi: weatherapiapikey

      # Changes the behaviour of links on the homepage,
      # ref: https://gethomepage.dev/configs/settings/#link-target
      target: _self

      # https://gethomepage.dev/configs/settings/#show-docker-stats
      showStats: true
  widgets.yaml:
    content: |
      ---
      # For configuration options and examples, please see:
      # https://gethomepage.dev/configs/service-widgets

      - openmeteo:
          units: imperial
          cache: 5 # Time in minutes to cache API responses, to stay within limits
          format: # optional, Intl.NumberFormat options
            maximumFractionDigits: 1

      # TODO: Widget seems to be broken
      # - unifi_console:
      #     url: http://192.168.2.1
      #     username: ${UNIFI_GATEWAY_USERNAME}
      #     password: ${UNIFI_GATEWAY_PASSWORD}

      - resources:
          label: TrueNAS Resources
          expanded: true
          cpu: true
          memory: true
          cputemp: true
          uptime: true
