---
- name: Restart systemd-logind
  ansible.builtin.systemd_service:
    name: systemd-logind
    state: restarted
- name: Refresh initramfs
  ansible.builtin.command:
    cmd: update-initramfs -u -k all
- name: Reboot machine
  ansible.builtin.reboot:
    msg: Rebooting machine in 5 seconds
