---
# cert-manager Helm Values Ref: https://artifacthub.io/packages/helm/cert-manager/cert-manager
# yaml-language-server: $schema=https://github.com/cert-manager/cert-manager/raw/refs/heads/master/deploy/charts/cert-manager/values.schema.json
crds:
  enabled: true
prometheus:
  enabled: true
  servicemonitor:
    enabled: true

replicaCount: 3
podDisruptionBudget:
  enabled: true
  minAvailable: 1
livenessProbe:
  enabled: true
# Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?var-datasource=default&var-cluster=&var-namespace=cert-manager&var-workload=cert-manager&var-type=All&orgId=1&refresh=10s&from=now-30d&to=now
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

webhook:
  replicaCount: 3
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  # Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?var-datasource=default&var-cluster=&var-namespace=cert-manager&var-workload=cert-manager-webhook&var-type=All&orgId=1&refresh=10s&from=now-30d&to=now
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 30m
      memory: 32Mi

cainjector:
  replicaCount: 3
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  # Based on: https://grafana.needham.wsbidev.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?var-datasource=default&var-cluster=&var-namespace=cert-manager&var-workload=cert-manager-cainjector&var-type=All&orgId=1&refresh=10s&from=now-30d&to=now
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

startupapicheck:
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 32Mi
