---
# Cilium Ref: https://artifacthub.io/packages/helm/cilium/cilium
# yaml-language-server: $schema=https://github.com/cilium/cilium/raw/refs/heads/main/install/kubernetes/cilium/values.schema.json
kubeProxyReplacement: true
bgpControlPlane:
  enabled: true

bpf:
  masquerade: true
egressGateway:
  enabled: true

# Ingress Controller & Envoy Proxy: https://docs.cilium.io/en/stable/network/servicemesh/l7-traffic-management/
# Needs a Loadbalancer configured in order to enable it
ingressController:
  enabled: true
  loadbalancerMode: dedicated
loadBalancer:
  l7:
    backend: envoy

# Enable Envoy Proxy in standalone DaemonSet.
envoy:
  enabled: true

# Transparent Encryption: https://docs.cilium.io/en/stable/security/network/encryption-wireguard/#enable-wireguard-in-cilium
# TODO: Failing to mount ipsec keys for some reason
# l7Proxy: false
# encryption:
#   enabled: true
#   encryption:
#     type: wireguard
externalIPs:
  enabled: true

k8sClientRateLimit:
  qps: 33
  burst: 48

# Resource Limits & Requests + Prometheus Monitoring + Grafana Dashboards
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
dashboards:
  enabled: true

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 25m
    memory: 256Mi
    ephemeral-storage: 8Mi
nodeinit:
  resources:
    limits:
      memory: 1024M
    requests:
      cpu: 100m
      memory: 100Mi
      ephemeral-storage: 8Mi
cgroup:
  autoMount:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 8Mi
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 128Mi
      ephemeral-storage: 8Mi
hubble:
  enabled: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      # TODO: uncommend when this issue is resolved: https://github.com/cilium/hubble-ui/issues/321#issuecomment-1571891834
      # - httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction
    enableOpenMetrics: true
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
  relay:
    enabled: true
    resources:
      limits:
        memory: 1024M
      requests:
        cpu: 100m
        memory: 64Mi
        ephemeral-storage: 8Mi
  ui:
    enabled: true
    backend:
      resources:
        limits:
          memory: 1024M
        requests:
          cpu: 100m
          memory: 64Mi
          ephemeral-storage: 8Mi
    frontend:
      resources:
        limits:
          memory: 1024M
        requests:
          cpu: 100m
          memory: 64Mi
          ephemeral-storage: 8Mi
