---
services:
  satisfactory-server:
    image: ghcr.io/wolveix/satisfactory-server:v1.9.9
    ports:
      - "7777:7777/tcp"
      - "7777:7777/udp"
      - "8888:8888/tcp"
    labels:
      # Homepage config
      # ref: https://gethomepage.dev/configs/docker/#automatic-service-discovery
      homepage.group: Docker Containers
      homepage.name: Satisfactory Server
      homepage.icon: si-steam

      # Whats up docker config
      wud.tag.include: ^v?\d+\.\d+\.\d+$$
    volumes:
      - datadir:/config
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

volumes:
  datadir:
