#cloud-config
# Cloud config Refs:
# - Base Config: https://cloudinit.readthedocs.io/en/latest/topics/base_config_reference.html
# - Module Config: https://cloudinit.readthedocs.io/en/latest/topics/modules.html
# - Examples: https://cloudinit.readthedocs.io/en/latest/topics/examples.html

packages:
  - fish
  - curl
  - ca-certificates
  - apt-transport-https
package_update: true
package_upgrade: true
package_reboot_if_required: true

runcmd:
  # - [ufw, allow, 22]
  # - [ufw, allow, 80]
  # - [ufw, allow, 179]
  # - [ufw, allow, 443]
  # - [ufw, allow, 2379]
  # - [ufw, allow, 2380]
  # - [ufw, allow, 4789]
  # - [ufw, allow, 6443]
  # - [ufw, allow, 8132]
  # - [ufw, allow, 8133]
  # - [ufw, allow, 9443]
  # - [ufw, allow, 10250]
  # - [ufw, allow, 10251]
  # - [ufw, allow, 10252]
  - [ufw, disable]
  # - [ufw, enable]

users:
  - name: vyas
    gecos: Vyas
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_import_id:
      - gh:vyas-n
