
resource "kubernetes_namespace" "external_secrets" {
  metadata {
    name = "external-secrets"
  }
}

resource "helm_release" "external_secrets" { # https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets
  name       = "external-secrets"
  chart      = "external-secrets"
  repository = "https://charts.external-secrets.io"
  version    = "0.18.2"

  namespace        = kubernetes_namespace.external_secrets.metadata[0].name
  create_namespace = false
  lint             = true
  timeout          = 300

  values = concat(
    [
      # We sort the fileset to preserve the ordering of the values files
      for file in sort(fileset(path.module, "helm/external-secrets/*.{yaml,yml}")) :
      # We decode & reencode to remove yaml comments & formatting from diff calculations
      yamlencode(yamldecode(file("${path.module}/${file}")))
      ], [
      yamlencode({}),
  ])
}

resource "kubernetes_secret" "onepassword_homelab_service_account" {
  metadata {
    name      = "onepassword-homelab-service-account"
    namespace = kubernetes_namespace.external_secrets.metadata[0].name
  }
  type = "Opaque"
  data = {
    token = var.external_secrets_onepassword_service_account_token
  }
}

resource "kubectl_manifest" "onepassword_homelab_cluster_secret_store" {
  yaml_body = yamlencode({
    apiVersion = "external-secrets.io/v1"
    kind       = "ClusterSecretStore"
    metadata = {
      name = "onepassword-homelab"
    }
    spec = {
      provider = {
        onepasswordSDK = {
          vault = "HomeLab"
          auth = {
            serviceAccountSecretRef = {
              name      = kubernetes_secret.onepassword_homelab_service_account.metadata[0].name
              namespace = kubernetes_namespace.external_secrets.metadata[0].name
              key       = "token"
            }
          }
        }
      }
    }
  })
  server_side_apply = true

  depends_on = [helm_release.external_secrets]
}

resource "kubernetes_namespace" "cert_manager" {
  metadata {
    name = "cert-manager"
    labels = {
      # fix webhook validation issues
      # ref: https://github.com/cert-manager/cert-manager/issues/6864#issuecomment-2027293360
      "cert-manager.io/disable-validation" : true
    }
  }
}

resource "helm_release" "cert_manager" { # https://artifacthub.io/packages/helm/cert-manager/cert-manager
  name       = "cert-manager"
  chart      = "cert-manager"
  repository = "https://charts.jetstack.io"
  version    = "1.15.4"

  namespace        = kubernetes_namespace.cert_manager.metadata[0].name
  create_namespace = false
  lint             = true
  timeout          = 300

  values = concat(
    [
      # We sort the fileset to preserve the ordering of the values files
      for file in sort(fileset(path.module, "helm/cert-manager/*.{yaml,yml}")) :
      # We decode & reencode to remove yaml comments & formatting from diff calculations
      yamlencode(yamldecode(file("${path.module}/${file}")))
      ], [
      yamlencode({}),
  ])
}

# ref: https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens
resource "kubernetes_secret" "cert_manager_cloudflare_creds" {
  metadata {
    name      = "cert-manager-cloudflare-creds"
    namespace = kubernetes_namespace.cert_manager.metadata[0].name
  }
  type = "Opaque"
  data = {
    api-token = var.cert_manager_cloudflare_api_token
  }
}

resource "kubernetes_secret" "cert_manager_zerossl_eab_creds" {
  metadata {
    name      = "cert-manager-zerossl-eab-creds"
    namespace = kubernetes_namespace.cert_manager.metadata[0].name
  }
  type = "Opaque"
  data = {
    eab_key_id = var.cert_manager_zerossl_eab_kid

    # ref: https://cert-manager.io/docs/configuration/acme/#external-account-bindings
    eab_hmac_key = var.cert_manager_zerossl_eab_hmac_key
  }
}

resource "kubectl_manifest" "zerossl_clusterissuer" {
  # ClusterIsssuer Ref: https://cert-manager.io/docs/configuration/acme/#configuration
  yaml_body = yamlencode({
    apiVersion = "cert-manager.io/v1"
    kind       = "ClusterIssuer"
    metadata = {
      name = "zerossl-prod"
    }
    spec = {
      acme = {
        email  = "me@vyas-n.com"
        server = "https://acme.zerossl.com/v2/DV90"
        externalAccountBinding = {
          keyID = var.cert_manager_zerossl_eab_kid
          keySecretRef = {
            name = kubernetes_secret.cert_manager_zerossl_eab_creds.metadata[0].name
            key  = "eab_hmac_key"
          }
        }
        # This secret gets autogenerated by the CRD, the name is just to identify it for later
        privateKeySecretRef = {
          name = "zerossl-prod-issuer-account-key"
        }
        solvers = [
          {
            selector = {
              dnsZones = [
                "vyas-n.dev"
              ]
            }
            dns01 = {
              cloudflare = {
                apiTokenSecretRef = {
                  name = kubernetes_secret.cert_manager_cloudflare_creds.metadata[0].name
                  key  = "api-token"
                }
              }
            }
          }
        ]
      }
    }
  })
  server_side_apply = true

  depends_on = [helm_release.cert_manager]
}

resource "kubernetes_namespace" "external_dns" {
  metadata {
    name = "external-dns"
  }
}

resource "kubernetes_secret" "external_dns_unifi_secret" {
  metadata {
    name      = "external-dns-unifi-secret"
    namespace = kubernetes_namespace.external_dns.metadata[0].name
  }
  type = "Opaque"
  data = {
    api-key = var.external_dns_unifi_secret_api_key
  }
}

resource "kubernetes_secret" "external_dns_cloudflare_secret" {
  metadata {
    name      = "external-dns-cloudflare-secret"
    namespace = kubernetes_namespace.external_dns.metadata[0].name
  }
  type = "Opaque"
  data = {
    apiKey = var.external_dns_cloudflare_api_token
  }
}

resource "helm_release" "external_dns_cloudflare" { # https://artifacthub.io/packages/helm/external-dns/external-dns
  name       = "external-dns-cloudflare"
  chart      = "external-dns"
  repository = "https://kubernetes-sigs.github.io/external-dns"
  version    = "1.19.0"

  namespace        = kubernetes_namespace.external_dns.metadata[0].name
  create_namespace = false
  lint             = true
  timeout          = 300

  values = [
    yamlencode(yamldecode(file("${path.module}/helm/external-dns-cloudflare/values.yaml"))), # remove yaml comments & formatting from diff calculations
    yamlencode({
      provider = {
        name = "cloudflare"
      }
      env = [{
        name = "CF_API_TOKEN"
        valueFrom = {
          secretKeyRef = {
            name = kubernetes_secret.external_dns_cloudflare_secret.metadata[0].name
            key  = "apiKey"
          }
        }
      }]
    })
  ]
}

# TODO: use unifi external-dns instead of cloudflare
# resource "helm_release" "external_dns_unifi" { # https://artifacthub.io/packages/helm/external-dns/external-dns
#   name       = "external-dns-unifi"
#   chart      = "external-dns"
#   repository = "https://kubernetes-sigs.github.io/external-dns"
#   version    = "1.19.0"

#   namespace        = kubernetes_namespace.external_dns.metadata[0].name
#   create_namespace = false
#   lint             = true
#   timeout          = 300

#   values = [
#     yamlencode(yamldecode(file("${path.module}/helm/external-dns-unifi/values.yaml"))), # remove yaml comments & formatting from diff calculations
#     yamlencode({
#       provider = {
#         webhook = {
#           env = [
#             { name  = "UNIFI_HOST"
#               value = "https://192.168.2.1"
#             },
#             { name  = "UNIFI_EXTERNAL_CONTROLLER"
#               value = "false"
#             },
#             {
#               name = "UNIFI_API_KEY"
#               valueFrom = {
#                 secretKeyRef = {
#                   name = kubernetes_secret.external_dns_unifi_secret.metadata[0].name
#                   key  = "api-key"
#                 }
#               }
#             }
#           ]
#         }
#       }
#     })
#   ]
# }


# resource "kubernetes_namespace" "kyverno" {
#   metadata {
#     name = "kyverno"
#   }
# }

# resource "helm_release" "kyverno" { # https://artifacthub.io/packages/helm/kyverno/kyverno
#   name       = "kyverno"
#   chart      = "kyverno"
#   repository = "https://kyverno.github.io/kyverno"
#   version    = "3.3.7"

#   namespace        = kubernetes_namespace.kyverno.metadata[0].name
#   create_namespace = false
#   lint             = true
#   timeout          = 300

#   values = [
#     yamlencode(yamldecode(file("${path.module}/helm/kyverno/values.yaml"))), # remove yaml comments & formatting from diff calculations
#     yamlencode({})
#   ]
# }

# resource "kubernetes_namespace" "policy_reporter" {
#   metadata {
#     name = "policy-reporter"
#   }
# }

# resource "helm_release" "policy_reporter" { # https://artifacthub.io/packages/helm/policy-reporter/policy-reporter
#   name       = "policy-reporter"
#   chart      = "policy-reporter"
#   repository = "oci://ghcr.io/kyverno/charts"
#   version    = "3.0.4"

#   namespace        = kubernetes_namespace.policy_reporter.metadata[0].name
#   create_namespace = false
#   lint             = true
#   timeout          = 300

#   values = [
#     yamlencode(yamldecode(file("${path.module}/helm/policy_reporter/values.yaml"))), # remove yaml comments & formatting from diff calculations
#     yamlencode({})
#   ]

#   depends_on = [helm_release.kyverno]
# }

# resource "kubernetes_namespace" "vertical_pod_autoscaler" {
#   metadata {
#     name = "vertical-pod-autoscaler"
#   }
# }

# resource "helm_release" "vertical_pod_autoscaler" { # https://artifacthub.io/packages/helm/cowboysysop/vertical-pod-autoscaler
#   name       = "vertical-pod-autoscaler"
#   chart      = "vertical-pod-autoscaler"
#   repository = "https://cowboysysop.github.io/charts"
#   version    = "10.0.0"

#   namespace        = kubernetes_namespace.vertical_pod_autoscaler.metadata[0].name
#   create_namespace = false
#   lint             = true
#   timeout          = 300

#   values = [
#     yamlencode(yamldecode(file("${path.module}/helm/vertical-pod-autoscaler/values.yaml"))), # remove yaml comments & formatting from diff calculations
#     yamlencode({})
#   ]
# }
