---
services:
  tsdproxy-1:
    image: docker.io/almeidapaulopt/tsdproxy:1.4.7
    configs:
      - source: tsdproxy.yaml
        target: /config/tsdproxy.yaml
        mode: "0440"
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /run/user/${HOST_USER_UID}/podman/podman.sock:/var/run/docker.sock
      - ./data/tsdproxy:/data:z
    labels:
      # Homepage config
      # ref: https://gethomepage.dev/configs/docker/#automatic-service-discovery
      homepage.group: Docker Containers
      homepage.name: TSDProxy
      homepage.icon: sh-tailscale-light.svg
      homepage.href: https://tsdproxy-1.tail5c72f1.ts.net

      # Tsdproxy config
      # ref: https://almeidapaulopt.github.io/tsdproxy/docs/docker
      tsdproxy.enable: true
      tsdproxy.name: tsdproxy-1
      tsdproxy.container_port: 8080
      tsdproxy.dash.icon: sh/tailscale-light

      # Whats up docker config
      wud.tag.include: ^v?\d+\.\d+\.\d+$
    restart: unless-stopped
configs:
  tsdproxy.yaml:
    file: config/tsdproxy.yaml
