---
# ref: https://artifacthub.io/packages/helm/goauthentik/authentik
authentik:
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.beryju.org, and is fully opt-in
  error_reporting:
    enabled: false
  secret_key: JqJsEP+VN+Zuduxm9LzBOVLPeFhGfTWIswJSLEp6ywaw7G29WHYbwKcbybDrLiHZhCvafcWlwQ==
  postgresql:
    password: &pg_password ThisIsNotASecurePassword

server:
  ingress:
    enabled: false
    # hosts:
    #   - authentik.domain.tld

postgresql:
  enabled: true
  auth:
    password: *pg_password
redis:
  enabled: true
