# GitHub Actions Workflows Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
---
name: CI
"on":
  push:
    branches:
      - develop
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
permissions: read-all
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          token: ${{ github.token }}
      - uses: oxsecurity/megalinter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@v3.1.3
        if: ${{ success() }} || ${{ failure() }}
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
          retention-days: 1
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: earthly/actions-setup@v1.0.8
        with:
          version: "latest"
      - name: Run build
        run: |
          earthly --allow-privileged +all
