---
# GitHub Actions Workflows Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: CI
"on":
  push:
    branches:
      - develop
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
permissions: {}
jobs:
  Lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: oxsecurity/megalinter/flavors/terraform@ec124f7998718d79379a3c5b39f5359952baf21d # v8.4.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        if: always() && !cancelled()
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
