---
# GitHub Actions Workflows Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: CI
"on":
  push:
    branches:
      - develop
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
permissions: {}
jobs:
  Lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: oxsecurity/megalinter/flavors/terraform@c217fe8f7bc9207062a084e989bd97efd56e7b9a # v8.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        if: always() && !cancelled()
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
