---
name: Nightly
"on":
  schedule:
    # ref: https://crontab.guru/#0_8_*_*_*
    # 08:00 UTC = 03:00 CDT
    - cron: 0 8 * * *
  workflow_dispatch: {}
permissions: {}
jobs:
  upgrade_trunk:
    name: Upgrade Trunk
    runs-on: ubuntu-latest
    permissions:
      contents: write # For trunk to create PRs
      pull-requests: write # For trunk to create PRs
    steps:
      # TODO: Setup GitHub App to create PR: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
      - uses: actions/checkout@v4.2.2
      # >>> Install your own deps here (npm install, etc) <<<
      - uses: trunk-io/trunk-action/upgrade@v1.2.3
