---
# GitHub Actions Workflows Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: PR
"on":
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
permissions: {}
defaults:
  run:
    shell: bash
jobs:
  PR:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - name: Check if PR Title is Conventional Commit
        uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
