---
name: Tag

"on":
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: SemVer compatible version to tag this repository and generate a release.

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write
  checks: write

jobs:
  tag:
    name: Tag Repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - run: echo "${{ github.event.inputs.version }}"
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ github.event.inputs.version }}
