[tools]
# Core tools
node = "latest"
usage = "latest"
# Keeping rust installed via rustup b/c mise doesn't have all the options that I want for changing rust versions between user-level & project-level
uv = "latest"
direnv = "latest"
go = "latest"
bun = "latest"

# Packages
"npm:prettier" = "latest"
"npm:markdown-table-formatter" = "latest"
"go:github.com/k0sproject/k0sctl" = "v0.27.1"
"go:github.com/terraform-linters/tflint" = "v0.60.0"
"cargo:zizmor" = "latest"
"cargo:just" = "latest"
"cargo:fd-find" = "latest"

[settings]
experimental = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["terraform", "python"]
npm.bun = true
