[tools]
# Core tools
node = "latest"
usage = "latest"
uv = "latest"
direnv = "latest"
go = "latest"

# Packages
"npm:prettier" = "latest"
"go:github.com/k0sproject/k0sctl" = "v0.25.1"

[settings]
experimental = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["terraform"]
