
[env]
ANSIBLE_CONFIG = "{{ config_root }}/ansible/ansible.cfg"

[settings]
experimental = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["terraform", "python"]
npm.bun = true

[tools]
# Core tools
node = "latest"
usage = "latest"
# Keeping rust installed via rustup b/c mise doesn't have all the options that I want for changing rust versions between user-level & project-level
uv = "latest"
direnv = "latest"
go = "latest"
bun = "latest"

# Packages
"npm:prettier" = "latest"
"npm:markdown-table-formatter" = "latest"
"go:github.com/k0sproject/k0sctl" = "v0.28.0"
"go:github.com/terraform-linters/tflint" = "v0.60.0"
"cargo:zizmor" = "latest"
"cargo:just" = "latest"
"cargo:fd-find" = "latest"

[tasks.setup-ansible]
run = "ansible/requirements.yml"
sources = ['ansible/requirements.yml', 'ansible/collections/**/*']
outputs = ['{{env.HOME}}/.ansible/collections/ansible_collections']

[tasks.docs]
run = '''
    #!/usr/bin/env nu

    for tf_directory in (glob infra/**/*.tf | path dirname | uniq) {
        terraform-docs markdown $tf_directory
    }
'''
sources = ['**/*.tf', '**/.terraform.lock.hcl']
outputs = ['**/README.md']

[tasks.format]
depends = ['docs']
run = '''
    just --fmt --unstable
    terraform fmt --recursive .
    prettier --write .
    markdown-table-formatter **/*.md
'''
